apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: taskmaster-api
  description: Task management API service
  annotations:
    github.com/project-slug: tusharkumarshahi/taskmaster-api
    jfrog.com/artifactory-repo: docker-trial
spec:
  type: service
  lifecycle: production
  owner: team-backend  
  system: taskmaster  
