apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: taskmaster-api
  description: Task management API service
  annotations:
    github.com/project-slug: tusharkumarshahi/taskmaster-api
    backstage.io/techdocs-ref: dir:.  
  links:
    - url: https://github.com/tusharkumarshahi/taskmaster-api
      title: Repository
      icon: github
    - url: https://sonarcloud.io/project/overview?id=tusharkumarshahi_taskmaster-api
      title: SonarQube
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: team-backend
  system: taskmaster
