apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: taskmaster-api
  description: Task management API service
  annotations:
    github.com/project-slug: tusharkumarshahi/taskmaster-api
    backstage.io/techdocs-ref: dir:.  
    sonarqube.org/project-key: tusharkumarshahi_taskmaster-api
    prometheus.io/rule: up
    
    grafana/dashboard-selector: "(uid == 'adx6qg5')"
    grafana/alert-label-selector: ".*"

    
  links:
    - url: https://github.com/tusharkumarshahi/taskmaster-api
      title: Repository
      icon: github
    - url: https://sonarcloud.io/project/overview?id=tusharkumarshahi_taskmaster-api
      title: SonarQube
      icon: dashboard
    - url: http://localhost:3001
      title: Grafana Dashboard
      icon: dashboard
    - url: http://localhost:9090
      title: Prometheus
      icon: dashboard
      
spec:
  type: service
  lifecycle: production
  owner: team-backend
  system: taskmaster
