apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: taskmaster-api
  description: Task management API service
  annotations:
    github.com/project-slug: tusharkumarshahi/taskmaster-api
    backstage.io/techdocs-ref: dir:.  
    sonarqube.org/project-key: tusharkumarshahi_taskmaster-api
    
    prometheus.io/rule: |
      rate(container_cpu_usage_seconds_total{id=~"/docker/.*"}[5m]) * 100
    prometheus.io/alert: 'all'
    grafana/dashboard-selector: "(tags @> 'backstage' || tags @> 'taskmaster')"
    grafana/alert-label-selector: "job=~\"cadvisor|node-exporter\""
    
  links:
    - url: https://github.com/tusharkumarshahi/taskmaster-api
      title: Repository
      icon: github
    - url: https://sonarcloud.io/project/overview?id=tusharkumarshahi_taskmaster-api
      title: SonarQube
      icon: dashboard
    - url: http://localhost:3001/d/adx6qg5
      title: Grafana Dashboard
      icon: dashboard
      
spec:
  type: service
  lifecycle: production
  owner: team-backend
  system: taskmaster
